---
apiVersion: v1
kind: Secret
metadata:
  name: tanzu-java-web-app.default.tap-values
stringData:
  values.yml: |
    ---
    # workload_name: example
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: false
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
